// Auto-generated by hub-codegen
// Do not edit manually

/** Hyperforge event types */
export type HyperforgeEvent = HyperforgeEvent_Status | HyperforgeEvent_Info | HyperforgeEvent_Error | HyperforgeEvent_Repo | HyperforgeEvent_SyncOp | HyperforgeEvent_SyncSummary;

/** Status information */
export interface HyperforgeEvent_Status {
  type: 'status';
  description: string;
  version: string;
}

/** General info message */
export interface HyperforgeEvent_Info {
  type: 'info';
  message: string;
}

/** Error message */
export interface HyperforgeEvent_Error {
  type: 'error';
  message: string;
}

/** Repository information */
export interface HyperforgeEvent_Repo {
  type: 'repo';
  description: string | null;
  mirrors: string[];
  name: string;
  origin: string;
  protected: boolean;
  visibility: string;
}

/** Sync diff result - repo operation */
export interface HyperforgeEvent_SyncOp {
  type: 'sync_op';
  forge: string;
  operation: string;
  repoName: string;
}

/** Sync summary */
export interface HyperforgeEvent_SyncSummary {
  type: 'sync_summary';
  forge: string;
  inSync: number;
  toCreate: number;
  toDelete: number;
  toUpdate: number;
  total: number;
}

